# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

SQ_VERSION:
  - 5.6.6 
  - LTS
  - DEV

MAVEN_VERSION:
  - 3.0.5
  - 3.1.1
  - 3.2.5
  - 3.3.9
  - 3.5.2

SLAVE:
  - linux

exclude:
  - SQ_VERSION: 5.6.6
    MAVEN_VERSION: 3.1.1
  - SQ_VERSION: 5.6.6
    MAVEN_VERSION: 3.2.5
  - SQ_VERSION: 5.6.6
    MAVEN_VERSION: 3.3.9
  - SQ_VERSION: 5.6.6
    MAVEN_VERSION: 3.5.2

  - SQ_VERSION: LTS
    MAVEN_VERSION: 3.0.5
  - SQ_VERSION: LTS
    MAVEN_VERSION: 3.5.2

  - SQ_VERSION: DEV
    MAVEN_VERSION: 3.0.5
  - SQ_VERSION: DEV
    MAVEN_VERSION: 3.1.1
  - SQ_VERSION: DEV
    MAVEN_VERSION: 3.2.5
  - SQ_VERSION: DEV
    MAVEN_VERSION: 3.3.9
